# Site settings
author: Jenelynrose Hopkins
title: The only true wisdom is in knowing you know nothing - Socrates
header-img: img/IMG_8659.JPG
email: jenelyn.hopkins@gmail.com
copyright_name: Jenelynrose Hopkins
description: > # this means to ignore newlines until "baseurl:"
  Learning is a circle that's never ending
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  Jenhop8786

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
